-- 插入默认的全局分类关键词数据到 GlobalCategoryKeyword 表
-- 如果数据已经存在（通过唯一键 keyword 冲突判断），则忽略插入，避免重复
INSERT INTO "GlobalCategoryKeyword" ("category", "keyword", "updatedAt") VALUES
-- 餐饮
('餐饮', '美团', CURRENT_TIMESTAMP),
('餐饮', '饿了么', CURRENT_TIMESTAMP),
('餐饮', '肯德基', CURRENT_TIMESTAMP),
('餐饮', '麦当劳', CURRENT_TIMESTAMP),
('餐饮', '星巴克', CURRENT_TIMESTAMP),
('餐饮', '喜茶', CURRENT_TIMESTAMP),
('餐饮', '海底捞', CURRENT_TIMESTAMP),
('餐饮', '外卖', CURRENT_TIMESTAMP),
('餐饮', '永福佳', CURRENT_TIMESTAMP),
('餐饮', '零食有鸣', CURRENT_TIMESTAMP),
('餐饮', '奶茶', CURRENT_TIMESTAMP),
('餐饮', '咖啡', CURRENT_TIMESTAMP),
('餐饮', '肠粉', CURRENT_TIMESTAMP),
('餐饮', '麻辣烫', CURRENT_TIMESTAMP),
('餐饮', '烧烤', CURRENT_TIMESTAMP),
('餐饮', '火锅', CURRENT_TIMESTAMP),
('餐饮', '曹记石磨粉', CURRENT_TIMESTAMP),
('餐饮', '普宁颗汁', CURRENT_TIMESTAMP),
('餐饮', '生鲜', CURRENT_TIMESTAMP),
('餐饮', '食品', CURRENT_TIMESTAMP),
-- 购物
('购物', '美宜佳', CURRENT_TIMESTAMP),
('购物', '超市', CURRENT_TIMESTAMP),
('购物', '便利店', CURRENT_TIMESTAMP),
('购物', '零食很忙', CURRENT_TIMESTAMP),
('购物', '水果店', CURRENT_TIMESTAMP),
('购物', '嘉盛水果', CURRENT_TIMESTAMP),
('购物', '东明商行', CURRENT_TIMESTAMP),
('购物', '百货', CURRENT_TIMESTAMP),
('购物', '商行', CURRENT_TIMESTAMP),
('购物', '淘宝', CURRENT_TIMESTAMP),
('购物', '天猫', CURRENT_TIMESTAMP),
('购物', '京东', CURRENT_TIMESTAMP),
('购物', '拼多多', CURRENT_TIMESTAMP),
('购物', '唯品会', CURRENT_TIMESTAMP),
('购物', '苏宁', CURRENT_TIMESTAMP),
('购物', '当当', CURRENT_TIMESTAMP),
('购物', '得物', CURRENT_TIMESTAMP),
-- 交通
('交通', '滴滴', CURRENT_TIMESTAMP),
('交通', '曹操出行', CURRENT_TIMESTAMP),
('交通', '12306', CURRENT_TIMESTAMP),
('交通', '铁路', CURRENT_TIMESTAMP),
('交通', '地铁', CURRENT_TIMESTAMP),
('交通', '公交', CURRENT_TIMESTAMP),
('交通', '高德打车', CURRENT_TIMESTAMP),
('交通', '花小猪', CURRENT_TIMESTAMP),
('交通', 'T3出行', CURRENT_TIMESTAMP),
('交通', '哈啰', CURRENT_TIMESTAMP),
('交通', '停车场', CURRENT_TIMESTAMP),
('交通', '中油碧辟', CURRENT_TIMESTAMP),
('交通', '石化', CURRENT_TIMESTAMP),
('交通', '顺易通', CURRENT_TIMESTAMP),
('交通', '智租换电', CURRENT_TIMESTAMP),
('交通', '互联互通停车', CURRENT_TIMESTAMP),
('交通', '高速公路', CURRENT_TIMESTAMP),
-- 娱乐
('娱乐', '猫眼', CURRENT_TIMESTAMP),
('娱乐', '淘票票', CURRENT_TIMESTAMP),
('娱乐', '电影', CURRENT_TIMESTAMP),
('娱乐', 'KTV', CURRENT_TIMESTAMP),
('娱乐', '王者荣耀', CURRENT_TIMESTAMP),
('娱乐', '和平精英', CURRENT_TIMESTAMP),
('娱乐', '台球', CURRENT_TIMESTAMP),
('娱乐', '小铁文娱', CURRENT_TIMESTAMP),
('娱乐', '银河台球', CURRENT_TIMESTAMP),
('娱乐', '街电', CURRENT_TIMESTAMP),
('娱乐', '竹芒充电', CURRENT_TIMESTAMP),
('娱乐', '怪兽充电', CURRENT_TIMESTAMP),
('娱乐', '游戏', CURRENT_TIMESTAMP),
-- 服务
('服务', '手机充值', CURRENT_TIMESTAMP),
('服务', '移动', CURRENT_TIMESTAMP),
('服务', '中国移动', CURRENT_TIMESTAMP),
('服务', '联通', CURRENT_TIMESTAMP),
('服务', '中国联通', CURRENT_TIMESTAMP),
('服务', '电信', CURRENT_TIMESTAMP),
('服务', '中国电信', CURRENT_TIMESTAMP),
('服务', '顺丰', CURRENT_TIMESTAMP),
('服务', '顺丰速运', CURRENT_TIMESTAMP),
('服务', '邮政', CURRENT_TIMESTAMP),
('服务', '快递', CURRENT_TIMESTAMP),
('服务', '医院', CURRENT_TIMESTAMP),
('服务', '门诊', CURRENT_TIMESTAMP),
('服务', '药店', CURRENT_TIMESTAMP),
('服务', '诊所', CURRENT_TIMESTAMP),
('服务', '保险', CURRENT_TIMESTAMP),
('服务', '缴费', CURRENT_TIMESTAMP),
('服务', '物业', CURRENT_TIMESTAMP),
('服务', '宽带', CURRENT_TIMESTAMP)
ON CONFLICT ("keyword") DO NOTHING;
